<?php
$id=$_GET['blog_id'];
$sql = "select * from `blogs` WHERE `blog_id`=$id";
$adapter = new adapter();
$blogs = $adapter->fetchAll($sql);
?>
<!DOCTYPE html>
<html>
	<head>
		<link rel="stylesheet" href="Model/Skin/css/style.css">
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title></title>
	</head>
	<body>
		<?php require_once "View/html/header.phtml" ?>
		<div class="d-flex">
			<h1></h1>
			<div class="mx-auto mt-2 ml-5 "> <a style="margin-left: 963px;" href="http://localhost/blog/BlogPost.php?a=edit&blog_id=<?php echo $id;	 ?>" class="btn btn-primary">Edit</a></div>
		</div>
		<div class="blogbg">
			<div class="blogdetail">
				<?php foreach ($blogs as $blog): ?>
  <img style="height: 25rem;" class="card-img-top" src="View/blog_post/blogimg/<?php echo $blog['image']; ?>" alt="blog image">
  <div class="card-body"><br><br>
    <h4 class="card-title"><?php echo $blog['title']; ?></h4><br><br>
    <h5 class="card-title"><?php echo $blog['short_description']; ?></h5><br><br>
    <p class="card-text"><?php echo $blog['description']; ?></p> <br><br>
   
    
</div>
			<?php endforeach; ?>
			</div>
		</div>
	</body>
</html>