<?php
$id=$_GET['blog_id'];
$sql = "SELECT * FROM `category`";
		$adapter = new adapter();
		$result = $adapter->fetchAll($sql);
$sql = "SELECT * FROM `blogs` WHERE `blog_id`=$id;";
		$blog = $adapter->fetchRow($sql);

?>
<!DOCTYPE html>
<html>
	<head>
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
		<link type="text/css" rel="stylesheet" href="Model/Skin/css/style.css">
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title></title>
	</head>
	<body>
		<?php require_once "View/html/header.phtml" ?>
		<div class="d-flex addblog ">
			<form action="http://localhost/blog/BlogPost.php?a=update" method="POST" enctype="multipart/form-data">
				<input type="text" class="form-control w-300" value="<?php echo $blog['blog_id'];?>" name="blog[blog_id]" hidden><br>
				<label >Title</label>
				<input type="text" class="form-control w-300" value="<?php echo $blog['title'];?>" name="blog[title]"><br>

				<label hidden>image</label>
				<div class="custom-file">
					<input type="file" class="custom-file-input" name="blogimg" hidden>
				</div>
				<label >Short Description</label>
				<textarea class="form-control" value="<?php echo $blog['short_description'];?>" name="blog[short_description]" id="exampleFormControlTextarea1" rows="2"><?php echo $blog['short_description'];?></textarea><br>
				<label >Description</label>
				<textarea class="form-control"placeho="<?php echo $blog['description'];?>" id="exampleFormControlTextarea1" name="blog[description]" rows="7"><?php echo $blog['description'];?></textarea><br>
				<label >status</label><br>
				<select name="blog[status]">
					<option value="active">active</option>
					<option value="inactive">inactive</option>
				</select>
				<br>
				<label >category</label><br>
				<select name="blog[category[][]"class="custom-select" multiple>
					<?php foreach ($result as $category): ?>
					<option value="<?php echo $category['category_id'];?>"><?php echo $category['title'];?></option>
					<?php endforeach; ?>
				</select>
					<a href="#">add new category</a><br>
				

					<button type="submit" class="btn btn-primary">Save</button>





			</div>
		</form>
	</div>
</body>
</html>