<?php
$sql = "SELECT * FROM `category`";
		$adapter = new adapter();
		$result = $adapter->fetchAll($sql);

?>

<!DOCTYPE html>
<html>
	<head>
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
		<link type="text/css" rel="stylesheet" href="Model/Skin/css/style.css">
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title></title>
	</head>
	<body>
		<?php require_once "View/html/header.phtml" ?>
		<div class="d-flex addblog ">
			<form action="http://localhost/blog/BlogPost.php?a=insert" method="POST" enctype="multipart/form-data">
				<label >Title</label>
				<input type="text" class="form-control w-300" id="" name="blog[title]"><br>
				<label >image</label>
				<div class="custom-file">
					<input type="file" class="custom-file-input" name="blogimg">
					<label class="custom-file-label" for="customFile">Choose file</label>
				</div>
				<label >Short Description</label>
				<textarea class="form-control" name="blog[short_description]" id="exampleFormControlTextarea1" rows="2"></textarea><br>
				<label >Description</label>
				<textarea class="form-control" id="exampleFormControlTextarea1" name="blog[description]" rows="7"></textarea><br>
				<label >status</label><br>
				<select name="blog[status]">
					<option value="active">active</option>
					<option value="inactive">inactive</option>
				</select>
				<br>
				<label >category</label><br>
				<select name="blog[category[][]"class="custom-select" multiple>
					<?php foreach ($result as $category): ?>
					<option value="<?php echo $category['category_id'];?>"><?php echo $category['title'];?></option>
					<?php endforeach; ?>
				</select>
					
					
				<div class="form-check">
					<input class="form-check-input" name="category[]" type="checkbox" value="" id="defaultCheck1">
					<label class="form-check-label" name="<?php echo $category['title'];?>">
						<?php echo $category['title'];?>
					</label>
				</div>

					<button type="submit" class="btn btn-primary">Submit</button>



			</div>
		</form>


<div class="form-popup" id="myForm">
  

	</div>
</body>
</html>